config/routes.rb
Rails.application.routes.draw do
  resources :t1s
  # 合同
  namespace :documents do
    # 房屋租赁合同
    resources :rental_agreements do
      collection do
        # 选择角色
        get :choice_role
        # 从房主新发布
        get :new_from_landlord
        # 从房客新发布
        get :new_from_tenant
        # 新建合同
        post :create_from_landlord
      end
    end

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landingpage#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rental_agreement.rb
class RentalAgreement < ApplicationRecord
end

# == Schema Information
#
# Table name: rental_agreements
#
#  id                 :integer          not null, primary key
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  landlord           :string
#  tenant             :string
#  house_location     :string
#  house_layout       :string
#  house_size         :integer
#  house_document     :string
#  house_mortgage     :boolean
#  house_usage        :string
#  house_maxpeoplenum :integer
#  lease_term_start   :datetime
#  lease_term_end     :datetime
#  rental_cycle       :string
#  rental_money       :integer
#  rental_way         :string
#  rental_date        :integer
#  rental_deposit     :integer
#  other_pays         :string
#  landlord_name      :string
#  landlord_phone     :string
#  landlord_idcode    :string
#  tenant_name        :string
#  tenant_phone       :string
#  tenant_idcode      :string
#

app/models/t1.rb
class T1 < ApplicationRecord
end

# == Schema Information
#
# Table name: t1s
#
#  id         :integer          not null, primary key
#  pd_id      :integer
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/documents/rental_agreements_controller.rb
class Documents::RentalAgreementsController < ApplicationController

  def index
    @rental_agreements = RentalAgreement.all
  end

  def show
    @rental_agreement = RentalAgreement.find(params[:id])
  end

  def new
    @rental_agreement = RentalAgreement.new
  end

  def create
    @rental_agreement = RentalAgreement.new(rental_agreement_params)
    if @rental_agreement.save
      redirect_to documents_rental_agreement_path(@rental_agreement)
    else
      render :new
    end
  end

  def update
    @rental_agreement = RentalAgreement.find(params[:id])
    if @rental_agreement.save
      redirect_to rental_agreements_path , notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    @rental_agreement = RentalAgreement.find(params[:id])
    @rental_agreement.destroy
    flash[:alert] = "已经删除"
    redirect_to rental_agreements_path
  end

  # 选择角色
  def choice_role
  end

  # 房主新建合同
  def new_from_landlord
    @rental_agreement = RentalAgreement.new
  end

  # 房客新建合同
  def new_from_tenant
    @rental_agreement = RentalAgreement.new
  end



  private

  def rental_agreement_params
    params.require(:rental_agreement).permit(:landlord, :tenant, :house_location, :house_layout, :house_size, :house_document, :house_mortgage, :house_usage, :house_maxpeoplenum, :lease_term_start, :lease_term_end, :rental_cycle, :rental_money, :rental_way, :rental_date, :rental_deposit, :other_pays, :landlord_name, :landlord_phone, :landlord_idcode, :tenant_name, :tenant_phone, :tenant_idcode)
  end

end

app/controllers/landingpage_controller.rb
class LandingpageController < ApplicationController
end

app/controllers/t1s_controller.rb
class T1sController < ApplicationController
  before_action :set_t1, only: [:show, :edit, :update, :destroy]

  # GET /t1s
  # GET /t1s.json
  def index
    @t1s = T1.all
  end

  # GET /t1s/1
  # GET /t1s/1.json
  def show
  end

  # GET /t1s/new
  def new
    @t1 = T1.new
  end

  # GET /t1s/1/edit
  def edit
  end

  # POST /t1s
  # POST /t1s.json
  def create
    @t1 = T1.new(t1_params)

    respond_to do |format|
      if @t1.save
        format.html { redirect_to @t1, notice: 'T1 was successfully created.' }
        format.json { render :show, status: :created, location: @t1 }
      else
        format.html { render :new }
        format.json { render json: @t1.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /t1s/1
  # PATCH/PUT /t1s/1.json
  def update
    respond_to do |format|
      if @t1.update(t1_params)
        format.html { redirect_to @t1, notice: 'T1 was successfully updated.' }
        format.json { render :show, status: :ok, location: @t1 }
      else
        format.html { render :edit }
        format.json { render json: @t1.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /t1s/1
  # DELETE /t1s/1.json
  def destroy
    @t1.destroy
    respond_to do |format|
      format.html { redirect_to t1s_url, notice: 'T1 was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_t1
      @t1 = T1.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def t1_params
      params.require(:t1).permit(:pd_id, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents/rental_agreements_helper.rb
module Documents::RentalAgreementsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze
  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end
  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning" 
  end
end

app/helpers/landingpage_helper.rb
module LandingpageHelper
end

app/helpers/t1s_helper.rb
module T1sHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2016 Rails101
        <br>Design by
        <a href="http://courses.growthschool.com/courses/rails-101/" target=_new>xdite</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Deal</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to("登入", '#') %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/documents/rental_agreements/_form.html.erb
<%= simple_form_for (['documents',@rental_agreement]) do |f| %>

<div class="form-group">
    <%= f.input :landlord, input_html: { class: "form-control"} %>
    <%= f.input :tenant, input_html: { class: "form-control"} %>
    <%= f.input :house_location, input_html: { class: "form-control"} %>
    <%= f.input :house_layout, input_html: { class: "form-control"} %>
    <%= f.input :house_size, input_html: { class: "form-control"} %>
    <%= f.input :house_document, input_html: { class: "form-control"} %>
    <%= f.input :house_mortgage, input_html: { class: "form-control"} %>
    <%= f.input :house_usage, input_html: { class: "form-control"} %>
    <%= f.input :house_maxpeoplenum, input_html: { class: "form-control"} %>
    <%= f.input :lease_term_start, input_html: { class: "form-control"} %>
    <%= f.input :lease_term_end, input_html: { class: "form-control"} %>
    <%= f.input :rental_cycle, input_html: { class: "form-control"} %>
    <%= f.input :rental_money, input_html: { class: "form-control"} %>
    <%= f.input :rental_way, input_html: { class: "form-control"} %>
    <%= f.input :rental_date, input_html: { class: "form-control"} %>
    <%= f.input :rental_deposit, input_html: { class: "form-control"} %>
    <%= f.input :other_pays, input_html: { class: "form-control"} %>
    <%= f.input :landlord_name, input_html: { class: "form-control"} %>
    <%= f.input :landlord_phone, input_html: { class: "form-control"} %>
    <%= f.input :landlord_idcode, input_html: { class: "form-control"} %>
    <%= f.input :tenant_name, input_html: { class: "form-control"} %>
    <%= f.input :tenant_phone, input_html: { class: "form-control"} %>
    <%= f.input :tenant_idcode, input_html: { class: "form-control"} %>
</div>
<%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
<% end %>

app/views/documents/rental_agreements/_form_for_landlord.html.erb
<%= simple_form_for (['documents',@rental_agreement])  do |f| %>

<div class="form-group">

    
<p>您房屋的位置在？</p>    
<%= f.input :house_location,label: false, input_html: { class: "form-control"} %>

<p>房屋面积有多少平？</p>
<%= f.input :house_size, label: false,input_html: { class: "form-control"} %>

<p>您对这个房子持有的证件是？</p>
<%= f.input :house_document, label: false,as: :check_boxes,collection: [["房屋所有权", "房屋所有权"], ["房屋买卖合同", "房屋买卖合同"],["原购房发票、契税", "原购房发票、契税"],["其他房屋来源证明文件", "其他房屋来源证明文件"]],:selected => "房屋所有权" %>

<p>该房屋是否抵押了呢？</p>
<%= f.input :house_mortgage,label: false, as: :radio_buttons, collection: [['已抵押', true],['未抵押',false]] %>

<p>房屋的用途为？</p>
<%= f.input :house_usage, label: false,as: :radio_buttons, collection: [['居住', 'live'],['商用','bussiness']] %>
<p>该房屋最多可居住人数</p>
<%= f.input :house_maxpeoplenum, label: false,input_html: { class: "form-control"} %>
<p>租赁期开始日期</p>
<%= f.input :lease_term_start, label: false,as: :date, start_year: Date.today.year - 12,
                              end_year: Date.today.year+12, discard_day: true,
                              order: [:month, :year], input_html: { class: "form-control"} %>
<p>租赁期结束日期</p>
<%= f.input :lease_term_end, label: false,as: :date, start_year: Date.today.year - 12,
                              end_year: Date.today.year+12, discard_day: true,
                              order: [:month, :year], input_html: { class: "form-control"} %>

<p>房租支付周期</p>
<%= f.input :rental_cycle, label: false,as: :radio_buttons, collection: [['每月', 'month'],['季度','season'],['半年','half_year'],['每年','year']] %>
<p>每次支付费用</p>
<%= f.input :rental_money, label: false,input_html: { class: "form-control"} %>
<p>支付方式为？</p>
<%= f.input :rental_way, label: false,as: :radio_buttons, collection: [['现金', 'cash'],['转账','transfer_accounts']] %>
<p>每期租金支付日期为？</p>
<%= f.input :rental_date, label: false,as: :radio_buttons, collection: [['每期首月1日', '1'],['每期首月10日','10'],['每期首月20日','20']] %>
<p>押金为？</p>
<%= f.input :rental_deposit, label: false,input_html: { class: "form-control"} %>
<p>额外费用由谁承担？(水、电、煤气、电视电话、车位、供暖、物业费)</p>
<%= f.input :other_pays, label: false,as: :radio_buttons, collection: [['房主承担', 'landlord'],['房客承担','tenant']] %>
<h6>房主信息</h6>
<p>房主姓名</p>
<%= f.input :landlord_name, label: false,input_html: { class: "form-control"} %>
<p>房主联系方式</p>
<%= f.input :landlord_phone, label: false,input_html: { class: "form-control"} %>
<p>房主身份证号</p>
<%= f.input :landlord_idcode, label: false,input_html: { class: "form-control"} %>
<!-- <h6>房客信息</h6>
<p>房客姓名</p>
<%#= f.input :tenant_name, label: false,input_html: { class: "form-control"} %>
<p>房客联系方式</p>
<%#= f.input :tenant_phone, label: false,input_html: { class: "form-control"} %>
<p>房客身份证号</p>
<%#= f.input :tenant_idcode, label: false,input_html: { class: "form-control"} %>
</div> -->
<%= f.submit "提交", class: "btn btn-primary", data: { disable_with: "提交中..." } %>
<% end %>

app/views/documents/rental_agreements/choice_role.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>选择您的身份</h2>

    <hr>
    <%= link_to("我是房主", new_from_landlord_documents_rental_agreements_path, class: "btn btn-primary") %>
    <br>
    <%= link_to("我是房客", new_from_tenant_documents_rental_agreements_path, class: "btn btn-primary") %>

</div>

app/views/documents/rental_agreements/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>编辑讨论版</h2>

    <hr>
    <%= render "form" %>

</div>

app/views/documents/rental_agreements/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("新建租赁合同", new_documents_rental_agreement_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
        <td>Creator</td>
        <td>Option</td>
      </tr>
    </thead>
    <tbody>
      <% @rental_agreements.each do |d| %>
      <tr>
        <td>
          <%= link_to('合同',documents_rental_agreement_path(d)) %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/documents/rental_agreements/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>新增讨论版</h2>

    <hr>
    <%= render "form" %>

</div>

app/views/documents/rental_agreements/new_from_landlord.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>新的合同</h2>

    <hr>
    <%= render "form_for_landlord" %>

</div>

app/views/documents/rental_agreements/show.html.erb
<div class="col-md-12">
<h1>房屋租赁合同</h1>
<p>出租人（甲方）： <strong> <%= @rental_agreement.landlord_name %> </strong> </p>
<p>承租人（乙方）：　待填</p>　　　　　　　
<p>
证件类型及编号：　　
<br>
根据《中华人民共和国合同法》《中华人民共和国城市房地产管理法》及其他有关法律、法规之规定，出租人和承租人在平等、自愿、协商一致的基础上达成如下协定：
<br>
<h2>第一条　房屋标准、租期、租金、用途</h2>
<br>
（一）承租人向出租人租用的房屋位于   <strong> <%= @rental_agreement.house_location %></strong>  ，建筑面积为　　<strong><%= @rental_agreement.house_size %></strong>　　平方米。
<br>
（二）房屋权属状况：甲方持有 <strong> <%= @rental_agreement.house_document %></strong> ，房屋
<% if @rental_agreement.house_mortgage %>
  <strong>有抵押</strong>.
<% else %>
  <strong>无抵押</strong>.
<% end %>
<br>
（三）房屋租赁用途为　　
<% if @rental_agreement.house_usage == 'live' %>
<strong>  居住　</strong> ；
居住人数最多不超过　 <strong> <%= @rental_agreement.house_maxpeoplenum %> </strong>　 人。
<% elsif %>  
<strong>  商用 </strong> ；
<% end %>
（四）房屋租赁期自　<strong><%= @rental_agreement.lease_term_start %></strong>　至　　<strong> <%= @rental_agreement.lease_term_end %></strong>，共计　n　个月。
<br>
<h2>第二条　租金及押金</h2>
（一）租金支付：　　<strong><%= @rental_agreement.rental_money %></strong>　　　元/
<% if @rental_agreement.rental_cycle == 'month' %>
<strong>月</strong>
<% elsif @rental_agreement.rental_cycle == 'season' %>
<strong>季</strong>
<% elsif @rental_agreement.rental_cycle == 'half_year' %>
<strong>半年</strong>
<% elsif @rental_agreement.rental_cycle == 'year' %>
 <strong>年</strong> 
<% end %>
，租赁该房屋租金每期：人民币　　

<strong> <%= @rental_agreement.rental_money %></strong>(换大写) 　　元整（￥：<strong> <%= @rental_agreement.rental_money %></strong>）。在本合同有效期内，不进行房屋租金调整，但若由法律的新增或修改，发生新的赋税，及甲方对该房增减设备时，甲、乙双方可协商修订租金。
<br>
（二）租金支付方式：

<% if @rental_agreement.rental_way=='cash' %>
  <strong>现金</strong>
<% else %>
  <strong>转账</strong> 
<% end %>
，付款时间：每次付款周期到期前 <strong><%= @rental_agreement.rental_date %></strong>日。
<br>
（三）押金：乙方支付甲方人民币<strong><%= @rental_agreement.rental_deposit %></strong>元整,此作为乙方履行本租约各项条款约定的保证，乙方不得以押金抵付房租，如乙方履行本租约的各项条款，在租约届满、乙方交还所租房屋并结清各项费用后，甲方应当即将押金退还承租人，不计利息。
<br>
<h2>第三条　其他相关费用的承担方式</h2>
（一）租赁期内的下列费用中，由 
<% if @rental_agreement.other_pays == 'landlord' %>
<strong>甲方</strong>  
<% else %>
<strong>乙方</strong>
<% end %>
 承担：(1)电费 (2)水费 (3)燃气费 (4)电视收视费 (5)电话费 (6)上网费 (7)车位费 (8)供暖费 (9)物业费。
<br>
（二）上诉费用执行市政及物业服务单位的征收标准，如遇相关部门调整，其调整差额由双方协商交纳。
<br>
（三）本合同中未列明的与房屋租赁有关的其他费用均由甲方承担，如乙方垫付应由甲方支付的费用，应提前告知甲方，甲方应根据乙方出示的相关交费凭据向乙方返还相关费用。
<br>
（四）因乙方（包括乙方来访者）保管不当或不合理使用，致使该房屋及其附属物品、设备设施发生损坏或故障的，乙方负责维修及承担赔偿的责任。
<h2>第四条　房屋交付与返还</h2>
<br>
（一）交付：甲方应于 12 年  月  日将房屋交付给乙方。
<br>
（一）甲方应保证房屋的建筑结构和设备设施符合建筑、消防、治安、卫生等方面的安全条件，不得危及人身安全；承租人保证遵守国家、北京市的法律法规规定以及房屋所在小区的物业管理规约。
<br>
（二）租赁期内，甲乙双方应共同保障房屋及其附属物品、设备设施处于适用和安全的状态：
<br>
1、对于房屋及其附属物品、设备设施因自然属性或合理使用而导致的损耗，乙方应及时通知甲方修复。甲方应在接到乙方通知后的10日内进行维修。逾期不维修的，乙方可代为维修，费用由甲方承担。因维修房屋影响乙方使用的，应相应减少租金或延长租赁期限。
<br>
2、因乙方(包括乙方来访者)保管不当或不合理使用，致使房屋及其附属物品、设备设施发生损坏或故障的，乙方应负责维修或承担赔偿责任。
<br>
<h2>第七条　转租</h2>
<br>
除甲乙双方另有约定以外，乙方需事先征得甲方书面同意，方可在租赁期内将房屋部分或全部转租给他人，并就受转租人的行为向甲方承担责任。
<br>
<h2>第八条　合同解除</h2>
<br>
（一）经甲乙双方协商一致，可以解除本合同。
<br>
（二）因不可抗力导致本合同无法继续履行的，本合同自行解除。
<br>
（三）甲方有下列情形之一的，乙方有权单方解除合同：
<br>
1、迟延交付房屋达七日的。
<br>
2、交付的房屋严重不符合合同约定或影响乙方安全、健康的。
<br>
3、不承担约定的维修义务，致使乙方无法正常使用房屋的。　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　。
<br>
（四）乙方有下列情形之一的，甲方有权单方解除合同，收回房屋：
<br>
1、不按照约定支付租金达七日的。
<br>
2、欠缴各项费用达单月租金额度的。
<br>
3、擅自改变房屋用途的。
<br>
4、擅自拆改变动或损坏房屋主体结构的。
<br>
5、保管不当或不合理使用导致附属物品、设备设施损坏并拒不赔偿的。
<br>
6、利用房屋从事违法活动、损害公共利益或者妨碍他人正常工作、生活的。
<br>
7、擅自将房屋转租给第三人的。
<br>
8、　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　 。
<br>
（五）其他法定的合同解除情形。
<br>
<h2>第九条　违约责任</h2>
<br>
（一）甲方有第八条第三款约定的情形之一的，应按月租金的200%向乙方支付违约金；乙方有第八条第四款约定的情形之一的，应按月租金的200%向甲方支付违约金，甲方并可要求乙方将房屋恢复原状或赔偿相应损失。
<br>
（二）租赁期内，甲方需提前收回房屋的，或乙方需提前退租的，应提前30日通知对方，并按月租金的200 %向对方支付违约金；甲方还应退还相应的租金及未履行的租金。
<br>
（三）甲方未按约定时间交付房屋或者乙方不按约定支付租金但未达到解除合同条件的，以及乙方未按约定时间返还房屋的，应按日租金的200%标准支付违约金。
<br>
（四）在租期届满后，由甲乙双方共同验收房屋。如有损坏，甲方有权用租赁押金维修及补偿，结算则以实际发生费用为准多退少补。
<br>
（五）乙方在租房期间应按有关规定交纳水电费、煤气费、有线收视费、电话费等各项费用，如租期满后仍有欠交费用，甲方有权用租赁押金偿还欠款及滞纳金，按实际发生费用为准，多退少补。
<br>
<h2>第十条 其他</h2>
<br>
(一)　 如果本租约到期,乙方不能退房而又未预先提出办理续租手续,即为拖期,拖期租金为正常租金的200%。
<br>
<h2>第十一条　合同争议的解决办法</h2>
<br>
出租人和承租人就本租约发生争议时，双方可协商解决；如无法达成一致意见，依法向有管辖权的人民法院起诉，或通过北京仲裁委员会仲裁解决争议。
</p>
<h2>第十二条　备注及补充</h2>
_____________________________
<br>
_____________________________
<br>
_____________________________
<br> 
本合同经双方签字后生效。本合同（及附件）一式两份，其中甲方执一份，乙方执一份。
<br>
本合同生效后，双方对合同内容的变更或补充应采取书面形式，作为本合同的附件。附件与本合同具有同等的法律效力。
<br>
出租人（甲方）签章:<strong> <%= @rental_agreement.landlord_name %></strong>
<br>
身份证号码: <strong><%= @rental_agreement.landlord_idcode %></strong> 
<br>
联系方式:<strong><%= @rental_agreement.landlord_phone %></strong>
<br>

承租人（乙方）签章：
<br>
委托代理人：
<br>
联系方式：
<br>
签订时间:<strong><%= @rental_agreement.created_at %></strong
</div>

app/views/landingpage/index.html.erb
<h1> Hello World! </h1>
<%= link_to("新建租赁合同", choice_role_documents_rental_agreements_path, class: "btn btn-primary pull-right") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deal</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>
    <%= render "common/footer" %>
  </body>
</html>

app/views/t1s/_form.html.erb
<%= simple_form_for(@t1) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :pd_id %>
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/t1s/edit.html.erb
<h1>Editing T1</h1>

<%= render 'form', t1: @t1 %>

<%= link_to 'Show', @t1 %> |
<%= link_to 'Back', t1s_path %>

app/views/t1s/index.html.erb
<p id="notice"><%= notice %></p>

<h1>T1s</h1>

<table>
  <thead>
    <tr>
      <th>Pd</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @t1s.each do |t1| %>
      <tr>
        <td><%= t1.pd_id %></td>
        <td><%= t1.name %></td>
        <td><%= link_to 'Show', t1 %></td>
        <td><%= link_to 'Edit', edit_t1_path(t1) %></td>
        <td><%= link_to 'Destroy', t1, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New T1', new_t1_path %>

app/views/t1s/new.html.erb
<h1>New T1</h1>

<%= render 'form', t1: @t1 %>

<%= link_to 'Back', t1s_path %>

app/views/t1s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pd:</strong>
  <%= @t1.pd_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @t1.name %>
</p>

<%= link_to 'Edit', edit_t1_path(@t1) %> |
<%= link_to 'Back', t1s_path %>